#!/usr/bin/env node

export const catalog = {
  mcpServers: [
    {
      id: 'design-patterns',
      level: 'recommended',
      description:
        'Required by the up-design-patterns skill. Installs from https://github.com/apolosan/design_patterns_mcp and must expose the design_patterns_* tools used by the package.',
      install: {
        strategy: 'git-bun-build',
        repo: 'https://github.com/apolosan/design_patterns_mcp.git',
        directoryName: 'design_patterns_mcp',
        buildSteps: ['bun install', 'bun run db:setup'],
      },
      scanPatterns: ['design_patterns_', 'design-patterns MCP server'],
    },
    {
      id: 'shadcn',
      level: 'recommended',
      description:
        'Used by the up-design-system skill to inspect components and generate install commands.',
      install: {
        strategy: 'npx-mcp',
        command: 'npx',
        args: ['-y', 'shadcn@latest', 'mcp'],
        package: 'shadcn@latest',
      },
      scanPatterns: ['shadcn_'],
    },
    {
      id: 'radix-mcp-server',
      level: 'recommended',
      description:
        'Used by the up-design-system skill for Radix Themes, Primitives, and Colors.',
      install: {
        strategy: 'npx-mcp',
        command: 'npx',
        args: ['-y', '@gianpieropuleo/radix-mcp-server@latest'],
        package: '@gianpieropuleo/radix-mcp-server@latest',
      },
      scanPatterns: ['radix_mcp_server_'],
    },
    {
      id: 'flyonui',
      level: 'recommended',
      description:
        'Used by the up-design-system skill to inspect and generate FlyonUI blocks.',
      install: {
        strategy: 'npx-mcp',
        command: 'npx',
        args: ['-y', 'flyonui-mcp'],
        package: 'flyonui-mcp',
      },
      scanPatterns: ['flyonui_'],
    },
  ],
  companionSkills: [
    {
      id: 'context7',
      level: 'recommended',
      description:
        'Referenced by up-tech-stack, up-design-patterns, and up-design-system for current library documentation lookup.',
      scanPatterns: ['/skill:context7', 'context7'],
    },
    {
      id: 'brave-search',
      level: 'recommended',
      description:
        'Referenced as the preferred current-web research skill.',
      scanPatterns: ['/skill:brave-search', 'brave-search'],
    },
    {
      id: 'web-search',
      level: 'recommended',
      description:
        'Referenced as a general web-search fallback skill.',
      scanPatterns: ['/skill:web-search', 'web-search'],
    },
    {
      id: 'web-fetch',
      level: 'recommended',
      description:
        'Referenced to fetch authoritative pages and docs during research activities.',
      scanPatterns: ['/skill:web-fetch', 'web-fetch'],
    },
  ],
  cliTools: [
    {
      id: 'npm',
      level: 'required',
      description: 'Needed by npm-based install flows and some generated setup instructions.',
      command: 'npm',
      install: { strategy: 'system' },
      scanPatterns: ['npm install', ' npm '],
    },
    {
      id: 'npx',
      level: 'recommended',
      description: 'Used as the portable fallback for Mermaid CLI and npm-based MCP launchers.',
      command: 'npx',
      install: { strategy: 'provided-by', provider: 'npm' },
      scanPatterns: ['npx @mermaid-js/mermaid-cli', ' npx '],
    },
    {
      id: 'mmdc',
      level: 'recommended',
      description: 'Mermaid CLI used by the documentation skill to render diagrams.',
      command: 'mmdc',
      install: {
        strategy: 'npm-package',
        package: '@mermaid-js/mermaid-cli',
        autoInstall: true,
      },
      scanPatterns: ['mmdc', '@mermaid-js/mermaid-cli'],
    },
    {
      id: 'docker',
      level: 'conditional',
      description: 'Referenced by the deployment skill for image build and containerized delivery.',
      command: 'docker',
      install: { strategy: 'system' },
      scanPatterns: ['docker build', '```dockerfile', ' docker '],
    },
    {
      id: 'docker-compose',
      level: 'conditional',
      description: 'Referenced by the deployment skill for local/full-stack orchestration.',
      command: 'docker-compose',
      aliases: ['docker compose'],
      install: { strategy: 'system' },
      scanPatterns: ['docker-compose'],
    },
    {
      id: 'jest',
      level: 'conditional',
      description: 'JavaScript/TypeScript unit-test tool explicitly referenced by the tech-stack skill.',
      command: 'jest',
      install: { strategy: 'npm-package', package: 'jest', autoInstall: true },
      scanPatterns: ['jest'],
    },
    {
      id: 'pytest',
      level: 'conditional',
      description: 'Python unit-test tool explicitly referenced by the tech-stack skill.',
      command: 'pytest',
      install: { strategy: 'pip-package', package: 'pytest', autoInstall: false },
      scanPatterns: ['pytest'],
    },
    {
      id: 'playwright',
      level: 'conditional',
      description: 'E2E/browser automation tool explicitly referenced by the tech-stack skill.',
      command: 'playwright',
      install: { strategy: 'npm-package', package: 'playwright', autoInstall: false },
      scanPatterns: ['playwright'],
    },
    {
      id: 'cypress',
      level: 'conditional',
      description: 'E2E/browser automation tool explicitly referenced by the tech-stack skill.',
      command: 'cypress',
      install: { strategy: 'npm-package', package: 'cypress', autoInstall: false },
      scanPatterns: ['cypress'],
    },
    {
      id: 'testcontainers',
      level: 'conditional',
      description: 'Integration-test infrastructure helper referenced by the tech-stack skill.',
      command: 'testcontainers',
      install: { strategy: 'manual' },
      scanPatterns: ['Testcontainers'],
    },
    {
      id: 'wiremock',
      level: 'conditional',
      description: 'API mocking tool referenced by the tech-stack skill.',
      command: 'wiremock',
      install: { strategy: 'manual' },
      scanPatterns: ['WireMock'],
    },
    {
      id: 'pact',
      level: 'conditional',
      description: 'Consumer-driven contract testing tool referenced by the tech-stack skill.',
      command: 'pact',
      install: { strategy: 'manual' },
      scanPatterns: ['Pact'],
    },
    {
      id: 'storybook',
      level: 'conditional',
      description: 'Component-workbench tool referenced by the tech-stack skill.',
      command: 'storybook',
      install: { strategy: 'npm-package', package: 'storybook', autoInstall: false },
      scanPatterns: ['Storybook'],
    },
    {
      id: 'playwright-visual',
      level: 'conditional',
      description: 'Visual regression category referenced through Percy, Chromatic, and Applitools.',
      command: 'percy',
      install: { strategy: 'manual' },
      scanPatterns: ['Percy', 'Chromatic', 'Applitools'],
    },
    {
      id: 'selenium',
      level: 'conditional',
      description: 'Browser automation option referenced by the tech-stack skill.',
      command: 'selenium',
      install: { strategy: 'manual' },
      scanPatterns: ['Selenium'],
    },
    {
      id: 'appium',
      level: 'conditional',
      description: 'Mobile E2E testing tool referenced by the tech-stack skill.',
      command: 'appium',
      install: { strategy: 'manual' },
      scanPatterns: ['Appium'],
    },
    {
      id: 'detox',
      level: 'conditional',
      description: 'Mobile E2E testing tool referenced by the tech-stack skill.',
      command: 'detox',
      install: { strategy: 'npm-package', package: 'detox', autoInstall: false },
      scanPatterns: ['Detox'],
    },
    {
      id: 'k6',
      level: 'conditional',
      description: 'Load/performance testing tool referenced by the tech-stack skill.',
      command: 'k6',
      install: { strategy: 'manual' },
      scanPatterns: ['k6'],
    },
    {
      id: 'locust',
      level: 'conditional',
      description: 'Load/performance testing tool referenced by the tech-stack skill.',
      command: 'locust',
      install: { strategy: 'pip-package', package: 'locust', autoInstall: false },
      scanPatterns: ['Locust'],
    },
    {
      id: 'jmeter',
      level: 'conditional',
      description: 'Load/performance testing tool referenced by the tech-stack skill.',
      command: 'jmeter',
      install: { strategy: 'manual' },
      scanPatterns: ['JMeter'],
    },
    {
      id: 'gatling',
      level: 'conditional',
      description: 'Load/performance testing tool referenced by the tech-stack skill.',
      command: 'gatling',
      install: { strategy: 'manual' },
      scanPatterns: ['Gatling'],
    },
    {
      id: 'owasp-zap',
      level: 'conditional',
      description: 'DAST tool referenced by the tech-stack skill.',
      command: 'zap',
      install: { strategy: 'manual' },
      scanPatterns: ['OWASP ZAP'],
    },
    {
      id: 'semgrep',
      level: 'conditional',
      description: 'Static analysis tool referenced by the tech-stack skill.',
      command: 'semgrep',
      install: { strategy: 'pip-package', package: 'semgrep', autoInstall: false },
      scanPatterns: ['Semgrep'],
    },
    {
      id: 'sonarqube',
      level: 'conditional',
      description: 'Static analysis platform referenced by the tech-stack skill.',
      command: 'sonarqube',
      install: { strategy: 'manual' },
      scanPatterns: ['SonarQube'],
    },
    {
      id: 'codeql',
      level: 'conditional',
      description: 'Static analysis/code scanning platform referenced by the tech-stack skill.',
      command: 'codeql',
      install: { strategy: 'manual' },
      scanPatterns: ['CodeQL'],
    },
    {
      id: 'snyk',
      level: 'conditional',
      description: 'SCA/security scanning tool referenced by the tech-stack skill.',
      command: 'snyk',
      install: { strategy: 'npm-package', package: 'snyk', autoInstall: false },
      scanPatterns: ['Snyk'],
    },
    {
      id: 'trivy',
      level: 'conditional',
      description: 'SCA/container scanning tool referenced by the tech-stack skill.',
      command: 'trivy',
      install: { strategy: 'manual' },
      scanPatterns: ['Trivy'],
    },
    {
      id: 'axe-core',
      level: 'conditional',
      description: 'Accessibility testing tool referenced by the tech-stack skill.',
      command: 'axe',
      install: { strategy: 'npm-package', package: 'axe-core', autoInstall: false },
      scanPatterns: ['axe-core'],
    },
    {
      id: 'lighthouse',
      level: 'conditional',
      description: 'Accessibility/performance auditing tool referenced by the tech-stack skill.',
      command: 'lighthouse',
      install: { strategy: 'npm-package', package: 'lighthouse', autoInstall: false },
      scanPatterns: ['Lighthouse'],
    },
    {
      id: 'pa11y',
      level: 'conditional',
      description: 'Accessibility testing tool referenced by the tech-stack skill.',
      command: 'pa11y',
      install: { strategy: 'npm-package', package: 'pa11y', autoInstall: false },
      scanPatterns: ['Pa11y'],
    },
    {
      id: 'stryker',
      level: 'conditional',
      description: 'Mutation testing tool referenced by the tech-stack skill.',
      command: 'stryker',
      install: { strategy: 'npm-package', package: '@stryker-mutator/core', autoInstall: false },
      scanPatterns: ['Stryker'],
    },
    {
      id: 'mutmut',
      level: 'conditional',
      description: 'Python mutation testing tool referenced by the tech-stack skill.',
      command: 'mutmut',
      install: { strategy: 'pip-package', package: 'mutmut', autoInstall: false },
      scanPatterns: ['mutmut'],
    },
    {
      id: 'pitest',
      level: 'conditional',
      description: 'Java mutation testing tool referenced by the tech-stack skill.',
      command: 'pitest',
      install: { strategy: 'manual' },
      scanPatterns: ['PITest'],
    },
    {
      id: 'fast-check',
      level: 'conditional',
      description: 'Property-based testing tool referenced by the tech-stack skill.',
      command: 'fast-check',
      install: { strategy: 'npm-package', package: 'fast-check', autoInstall: false },
      scanPatterns: ['fast-check'],
    },
    {
      id: 'hypothesis',
      level: 'conditional',
      description: 'Property-based testing tool referenced by the tech-stack skill.',
      command: 'hypothesis',
      install: { strategy: 'pip-package', package: 'hypothesis', autoInstall: false },
      scanPatterns: ['Hypothesis'],
    },
    {
      id: 'quickcheck',
      level: 'conditional',
      description: 'Property-based testing family referenced by the tech-stack skill.',
      command: 'quickcheck',
      install: { strategy: 'manual' },
      scanPatterns: ['QuickCheck'],
    },
    {
      id: 'libfuzzer',
      level: 'conditional',
      description: 'Fuzzing tool referenced by the tech-stack skill.',
      command: 'libfuzzer',
      install: { strategy: 'manual' },
      scanPatterns: ['libFuzzer'],
    },
    {
      id: 'afl++',
      level: 'conditional',
      description: 'Fuzzing tool referenced by the tech-stack skill.',
      command: 'afl++',
      install: { strategy: 'manual' },
      scanPatterns: ['AFL++'],
    },
    {
      id: 'oss-fuzz',
      level: 'conditional',
      description: 'Fuzzing service referenced by the tech-stack skill.',
      command: 'oss-fuzz',
      install: { strategy: 'manual' },
      scanPatterns: ['OSS-Fuzz'],
    },
  ],
};

export const allDependencies = [
  ...catalog.mcpServers.map((item) => ({ type: 'mcp', ...item })),
  ...catalog.companionSkills.map((item) => ({ type: 'skill', ...item })),
  ...catalog.cliTools.map((item) => ({ type: 'cli', ...item })),
];

export function getSkillFiles(rootDir) {
  return new URL('../skills/', rootDir);
}
